---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  server:
      enable-self-preservation: false       # 关闭自我保护模式（缺省为打开）
      eviction-interval-timer-in-ms: 1000   # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
  client:
      serviceUrl:
         defaultZone:  http://localhost:8000/eureka/
      register-with-eureka: false
      fetch-registry: false
#security:
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: admin

---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2
server:
  port: 8001
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/
    register-with-eureka: false
    fetch-registry: false
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer3
server:
  port: 8002
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
    register-with-eureka: false
    fetch-registry: false